### ISSUE TITLE
Unsolved dependencies

### ISSUE THREAD

**Issue by brunohanai** [Soolan/mava-project#1] opened 2016-06-09 17:48 UTC
$ composer update

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/admin-bundle dev-master -> satisfiable by sonata-project/admin-bundle[dev-master].
    - sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle ^3.0 -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - Can only install one of: sonata-project/admin-bundle[dev-master, 3.x-dev].
    - Installation request for sonata-project/doctrine-orm-admin-bundle dev-master -> satisfiable by sonata-project/doctrine-orm-admin-bundle[dev-master].
```

**Comment by Soolan** [comment] 2016-06-10 07:28
Yes I saw that. Thanks for addressing it.
The problem is there are so many unresolved dependencies coming from FOSUserBundle ans Sonata Bundle(s) ans Symfony 3. I'm trying to find a way to make it work while having all parties together.
Because in the future chapters we need them.
I wish I could seek other alternatives but unfortunately the book has been published and I can't change anything there...

**Comment by Carteni** [comment] 2016-09-08 13:19
Hi Soolan, great job for your book.
Here https://github.com/Carteni/my-mava-project there is a "parallel" repo in which each branch name is related to a chapter (i'm on chapter 8 at the moment).
I'm using Symfony ^3.1 version but still remain the known issues with SonataUserBundle (when FOSUserBundle v.2 will be released maybe issues will be resolved).
I hope that this helps.

**Comment by Soolan** [comment] 2016-09-09 00:04
Thanks man. This is so kind of you.
Guys please use that repo for the time being till I do a major update on mine with a lot of changes (hopefully by the end of this year).

**Closed by Soolan** 2016-09-09 00:04 UTC
